name: test

on:
  push:
    branches-ignore:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build amd
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: usbipiceproject/usbipice-worker:amd
          file: deploy/Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=usbipiceproject/usbipice-worker:amd
          cache-to: type=inline, mode=max

      - name: Compose Up
        run: docker compose -f deploy/test_compose.yml up -d

      - name: Wait for compose
        run: sleep 2m

      - name: Run Tests
        run: docker compose -f deploy/test_compose.yml exec client .venv/bin/python3 tests/pulsecount_stack.py

      - name: Compose Logs
        run: docker compose -f deploy/test_compose.yml logs

      - name: Compose Down
        run: docker compose -f deploy/test_compose.yml down
