name: test

on:
  push:
    branches:
      - 'tests'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Compose Up
        run: docker compose -f deploy/test_compose.yml up -d

      - name: Wait for compose
        run: sleep 2m

      - name: Run tests
        run: docker compose exec client .venv/bin/python3 tests/pulsecount_stack.py

      - name: Compose Down
        run: docker compose -f deploy/test_compose.yml down